### ISSUE TITLE
Script error "tar: unrecognized option '--xattrs'"

### ISSUE THREAD

**Issue by jejanim** [evilegidiux/tarbackup#1]
Hey there,

just gave your script a try.
Seems to throw a tar error for wrong syntax for me.
Output:
````
$ sudo ./tarbackup
No LSB modules are available.
writing exclusions to temporary file...
creating tarball, please wait...
tar: unrecognized option '--xattrs'
Try `tar --help' or `tar --usage' for more information.
an error occurred, aborting!
removing temporary file...
````

I am on debian wheezy.

UPDATE: the --xattrs flag seems to be working on CentOS only, see [here](https://www.bountysource.com/issues/5911231-tar-xattrs-only-works-on-centos)

**Comment by evilegidiux** [comment]
No the --xattrs works fine for me even on debian. It's  just that the tar version on Wheezy doesn't support it yet. You can run the script deleting the --xattrs option in the main tar command (if you don't need tar to preserve extended attributes) or install the version of tar from wheezy-backports.

**Comment by jejanim** [comment]
Yea that seemed to be the solution for me as well but simply deleting the --xattrs does not do the trick.
I'll try the other version first - thanks.

**Comment by jejanim** [comment]
The backport tar version supports the flag and thus the script works flawlessly now :)
