### ISSUE TITLE
Tar exit code 1 deletes complete archive.

### ISSUE THREAD

**Issue by jejanim** [evilegidiux/tarbackup#2]
I get a lot of 
````
./sys: file changed as we read it
````
during the backup process even though tar should ignore /sys.
The backup runs into completion and then fails while deleting the whole archive.

**Comment by evilegidiux** [comment]
It's just a matter of settings. I put sys/* in the sys_excluded variable in the script so it excludes all inside the sys directory but not the directory itself. I like this way to avoid having to recreate it by hand on restore. Most of the times this doesn't happen to me, maybe you have some process that modifies stuff there. The warning causes tar to exit with status 1, and the script does react on the error deleting the tarball and temporary file

Anyway there are several thing that could be done:

1) You could just modify the pattern to exclude the whole directory (from "sys/*" to "sys" in the settings); 

2) Try to minimize activity during backup, or running the script from a live cd (you could use the -p option from there)

**Comment by jejanim** [comment]
True, in that case the empty folders make sense.
I'll adjust the pattern then.
